# Generated by Django 3.1.7 on 2021-03-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, verbose_name='Título')),
                ('completo', models.BooleanField(default=False, verbose_name='Completo?')),
                ('data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
        ),
    ]
